name: Build
on:
  push:
    branches-ignore:
      - data
    tags:
      - '**'
  pull_request:
    branches-ignore:
      - data

jobs:
  build-android-armeabi-v7a:
    name: Build for Android (armeabi-v7a)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: master

      - name: Build armeabi-v7a
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozerv7
        with:
          repository_root: master
          workdir: src/armeabi-v7a
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: netbright_armeabi-v7a.apk
          path: ${{ steps.buildozerv7.outputs.filename }}
          retention-days: 5

  build-android-arm64-v8a:
    name: Build for Android (arm64-v8a)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: master

      - name: Build arm64-v8a
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozerv8
        with:
          repository_root: master
          workdir: src/arm64-v8a
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: netbright_arm64-v8a.apk
          path: ${{ steps.buildozerv8.outputs.filename }}
          retention-days: 5
